---
- name: download artifact
  block:
    - name: copy from local
      copy:
         src: ./target/applogin-1.1.war
         dest: /tmp
  rescue:
    - name: download from artifact
      get_url:
        url: https://github.com/tejesh555/applogin/raw/master/target/applogin.war
        dest: /tmp

- name: copy artifact 
  copy:
     src: /tmp/applogin.war
     dest: /opt/tomcat/latest/webapps/applogin.war
     owner: tomcat
     group: tomcat
     remote_src: yes
  notify:
    - restart tomcat after deploy
  

