---
- hosts: all
  tasks:
          - name: ping1
            ping:
                    data: "{{ item }}"
            with_items:
                    - tejesh
                    - arshad
                    - nagendra
                    - jagan

          - name: ping2
            ping:
